package main

import (
	"bytes"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	apierrors "github.com/larsartmann/go-hotspot/internal/errors"
	"github.com/larsartmann/go-hotspot/internal/hotspot"
)

func TestFileFilter(t *testing.T) {
	cases := []struct {
		name     string
		filter   fileFilter
		path     string
		expected bool
	}{
		{"go file, default filter", fileFilter{exts: []string{".go"}}, "main.go", true},
		{"non-go file, .go filter", fileFilter{exts: []string{".go"}}, "script.py", false},
		{"test file, tests excluded", fileFilter{exts: []string{".go"}, includeTests: false}, "main_test.go", false},
		{"test file, tests included", fileFilter{exts: []string{".go"}, includeTests: true}, "main_test.go", true},
		{"generated file, excluded", fileFilter{exts: []string{".go"}}, "foo.pb.go", false},
		{"generated file, included", fileFilter{exts: []string{".go"}, includeGenerated: true}, "foo.pb.go", true},
		{"vendor path excluded", fileFilter{exts: []string{".go"}}, "vendor/lib.go", false},
		{"nested vendor excluded", fileFilter{exts: []string{".go"}}, "foo/vendor/lib.go", false},
		{"path prefix match", fileFilter{exts: []string{".go"}, prefixes: []string{"pkg/"}}, "pkg/main.go", true},
		{"path prefix no match", fileFilter{exts: []string{".go"}, prefixes: []string{"pkg/"}}, "other/main.go", false},
		{"empty prefix ignored", fileFilter{exts: []string{".go"}}, "main.go", true},
		{"no exts = all pass", fileFilter{}, "anything.txt", true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := tc.filter.keep(tc.path); got != tc.expected {
				t.Errorf("keep(%q) = %v, want %v", tc.path, got, tc.expected)
			}
		})
	}
}

func TestIsGenerated(t *testing.T) {
	cases := map[string]bool{
		"foo.pb.go":    true,
		"foo.gen.go":   true,
		"foo_gen.go":   true,
		"foo.pb.gw.go": true,
		"foo.templ.go": true,
		"main.go":      false,
		"generated.go": false,
		"foo.pb.txt":   false,
	}
	for path, want := range cases {
		if got := isGenerated(path); got != want {
			t.Errorf("isGenerated(%q) = %v, want %v", path, got, want)
		}
	}
}

func TestIsGeneratedContent(t *testing.T) {
	dir := t.TempDir()

	genFile := filepath.Join(dir, "generated.go")
	if err := os.WriteFile(
		genFile,
		[]byte("// Code generated by protoc. DO NOT EDIT.\n\npackage main\n"),
		0o600,
	); err != nil {
		t.Fatal(err)
	}

	if !isGeneratedContent(genFile) {
		t.Error("isGeneratedContent should detect generated header")
	}

	normalFile := filepath.Join(dir, "normal.go")
	if err := os.WriteFile(normalFile, []byte("package main\n\nfunc main() {}\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	if isGeneratedContent(normalFile) {
		t.Error("isGeneratedContent should not flag normal files")
	}

	missingFile := filepath.Join(dir, "nonexistent.go")
	if isGeneratedContent(missingFile) {
		t.Error("isGeneratedContent should return false for missing files")
	}
}

func TestParseComplexityMetric(t *testing.T) {
	cases := map[string]hotspot.ComplexityMetric{
		"cyclomatic":  hotspot.MetricCyclomatic,
		"indentation": hotspot.MetricIndentation,
		"indent":      hotspot.MetricIndentation,
		"sloc":        hotspot.MetricSLOC,
		"loc":         hotspot.MetricSLOC,
		"lines":       hotspot.MetricSLOC,
		"unknown":     hotspot.MetricCyclomatic,
	}
	for in, want := range cases {
		if got := parseComplexityMetric(in); got != want {
			t.Errorf("parseComplexityMetric(%q) = %v, want %v", in, got, want)
		}
	}
}

func TestParseChurnMetric(t *testing.T) {
	cases := map[string]hotspot.ChurnMetric{
		"weighted": hotspot.ChurnWeighted,
		"commits":  hotspot.ChurnCommits,
		"commit":   hotspot.ChurnCommits,
		"lines":    hotspot.ChurnLines,
		"raw":      hotspot.ChurnLines,
		"unknown":  hotspot.ChurnWeighted,
	}
	for in, want := range cases {
		if got := parseChurnMetric(in); got != want {
			t.Errorf("parseChurnMetric(%q) = %v, want %v", in, got, want)
		}
	}
}

func TestSplitCSV(t *testing.T) {
	cases := []struct {
		input    string
		expected []string
	}{
		{"", nil},
		{"  ", nil},
		{".go", []string{".go"}},
		{".go,.py,.ts", []string{".go", ".py", ".ts"}},
		{".go, .py , .ts", []string{".go", ".py", ".ts"}},
		{",,", nil},
	}
	for _, tc := range cases {
		got := splitCSV(tc.input)
		if len(got) != len(tc.expected) {
			t.Errorf("splitCSV(%q) = %v, want %v", tc.input, got, tc.expected)

			continue
		}

		for i := range got {
			if got[i] != tc.expected[i] {
				t.Errorf("splitCSV(%q)[%d] = %q, want %q", tc.input, i, got[i], tc.expected[i])
			}
		}
	}
}

func TestHasAuthor(t *testing.T) {
	names := []string{"Alice", "Bob", "Carol"}
	if !hasAuthor(names, "Alice") {
		t.Error("hasAuthor should find Alice")
	}

	if !hasAuthor(names, "alice") {
		t.Error("hasAuthor should be case-insensitive")
	}

	if hasAuthor(names, "Dave") {
		t.Error("hasAuthor should not find Dave")
	}

	if hasAuthor(nil, "Alice") {
		t.Error("hasAuthor should return false for nil slice")
	}
}

func TestRunVersion(t *testing.T) {
	var buf bytes.Buffer

	err := run([]string{"--version"}, &buf, io.Discard, time.Now())
	if err != nil {
		t.Fatalf("run --version returned error: %v", err)
	}

	out := buf.String()
	if !strings.Contains(out, "go-hotspot version") {
		t.Errorf("version output missing header, got: %q", out)
	}
}

// setupMiniRepo creates a temporary git repository with a single .go file,
// changes into it, and commits it. Used by exit-code integration tests that
// need a real git repo to operate on.
func setupMiniRepo(t *testing.T) {
	t.Helper()

	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git not available")
	}

	dir := t.TempDir()
	t.Chdir(dir)

	execGit(t, "init")
	execGit(t, "config", "user.name", "Test")
	execGit(t, "config", "user.email", "test@example.com")

	goFile := filepath.Join(dir, "main.go")
	if err := os.WriteFile(goFile, []byte("package main\nfunc main() {}\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	execGit(t, "add", "main.go")

	cmd := exec.CommandContext(t.Context(), "git", "commit", "-m", "init")

	cmd.Env = append(os.Environ(),
		"GIT_AUTHOR_DATE=2026-01-01T10:00:00Z",
		"GIT_COMMITTER_DATE=2026-01-01T10:00:00Z",
	)
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git commit: %v\n%s", err, out)
	}
}

func execGit(t *testing.T, args ...string) {
	t.Helper()

	cmd := exec.CommandContext(t.Context(), "git", args...)
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git %s: %v\n%s", strings.Join(args, " "), err, out)
	}
}

func TestExitCodeSuccess(t *testing.T) {
	t.Parallel()

	var buf bytes.Buffer

	err := run([]string{"--version"}, &buf, io.Discard, time.Now())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if code := apierrors.ExitCode(err); code != 0 {
		t.Errorf("ExitCode = %d, want 0 (success)", code)
	}
}

func TestExitCodeUsage(t *testing.T) {
	t.Parallel()

	err := run([]string{"--bad-flag"}, io.Discard, io.Discard, time.Now())
	if err == nil {
		t.Fatal("expected error for invalid flag")
	}

	if code := apierrors.ExitCode(err); code != 1 {
		t.Errorf("ExitCode = %d, want 1 (EX_USAGE)", code)
	}
}

func TestExitCodeGitFailure(t *testing.T) { //nolint:paralleltest // uses t.Chdir — mutates process CWD
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git not available")
	}

	dir := t.TempDir()
	t.Chdir(dir)

	err := run(nil, io.Discard, io.Discard, time.Now())
	if err == nil {
		t.Fatal("expected error in non-git directory")
	}

	if code := apierrors.ExitCode(err); code != 69 {
		t.Errorf("ExitCode = %d, want 69 (EX_UNAVAILABLE)", code)
	}
}

func TestExitCodeThreshold(t *testing.T) { //nolint:paralleltest // uses t.Chdir via setupMiniRepo
	setupMiniRepo(t)

	err := run([]string{"--fail-above", "0.000001"}, io.Discard, io.Discard, time.Now())
	if err == nil {
		t.Fatal("expected threshold-exceeded error")
	}

	if code := apierrors.ExitCode(err); code != 2 {
		t.Errorf("ExitCode = %d, want 2 (threshold)", code)
	}
}

func TestParseFailRisk(t *testing.T) {
	t.Parallel()

	cases := []struct {
		input string
		want  float64
	}{
		{"critical", 0.15},
		{"high", 0.08},
		{"medium", 0.03},
		{"low", 0.01},
		{"CRITICAL", 0.15},
		{"  high  ", 0.08},
		{"", 0},
		{"unknown", 0},
	}

	for _, tc := range cases {
		got := parseFailRisk(tc.input)
		if got != tc.want {
			t.Errorf("parseFailRisk(%q) = %v, want %v", tc.input, got, tc.want)
		}
	}
}

func TestHasVersionFlag(t *testing.T) {
	t.Parallel()

	cases := []struct {
		args []string
		want bool
	}{
		{[]string{"--version"}, true},
		{[]string{"-version"}, true},
		{[]string{"--version", "--bad-flag"}, true},
		{[]string{"--bad-flag", "--version"}, true},
		{[]string{"--help"}, false},
		{nil, false},
	}

	for _, tc := range cases {
		if got := hasVersionFlag(tc.args); got != tc.want {
			t.Errorf("hasVersionFlag(%v) = %v, want %v", tc.args, got, tc.want)
		}
	}
}

func TestVersionBeforeParse(t *testing.T) {
	t.Parallel()

	var buf bytes.Buffer

	err := run([]string{"--version", "--bad-flag"}, &buf, io.Discard, time.Now())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if !strings.Contains(buf.String(), "go-hotspot version") {
		t.Errorf("expected version output, got: %s", buf.String())
	}
}

func TestOutputToFile(t *testing.T) { //nolint:paralleltest // uses t.Chdir via setupMiniRepo
	setupMiniRepo(t)

	reportPath := filepath.Join(t.TempDir(), "report.txt")

	err := run([]string{"--output", reportPath}, io.Discard, io.Discard, time.Now())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	data, readErr := os.ReadFile(reportPath)
	if readErr != nil {
		t.Fatal(readErr)
	}

	if len(data) == 0 {
		t.Error("expected non-empty output file")
	}
}

func TestMinCommitsFilter(t *testing.T) { //nolint:paralleltest // uses t.Chdir via setupMiniRepo
	setupMiniRepo(t)

	// Mini repo has 1 commit. --min-commits 2 should produce no results.
	var buf bytes.Buffer

	err := run([]string{"--min-commits", "2", "--format", "csv", "--no-coupling"}, &buf, io.Discard, time.Now())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	output := strings.TrimSpace(buf.String())
	if strings.Contains(output, "main.go") {
		t.Errorf("expected main.go filtered out with --min-commits 2, got: %s", output)
	}
}

func TestAuthorFilter(t *testing.T) { //nolint:paralleltest // uses t.Chdir via setupMiniRepo
	setupMiniRepo(t)

	// Author "Test" should include main.go; "Nobody" should exclude it.
	var buf bytes.Buffer

	err := run([]string{"--author", "Test", "--format", "csv", "--no-coupling"}, &buf, io.Discard, time.Now())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if !strings.Contains(buf.String(), "main.go") {
		t.Errorf("expected main.go with --author Test, got: %s", buf.String())
	}

	// --author Nobody should produce empty results.
	buf.Reset()
	err = run([]string{"--author", "Nobody", "--format", "csv", "--no-coupling"}, &buf, io.Discard, time.Now())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if strings.Contains(buf.String(), "main.go") {
		t.Errorf("expected main.go excluded with --author Nobody, got: %s", buf.String())
	}
}

func TestNoHeader(t *testing.T) { //nolint:paralleltest // uses t.Chdir via setupMiniRepo
	setupMiniRepo(t)

	var buf bytes.Buffer

	err := run([]string{"--no-header", "--no-coupling"}, &buf, io.Discard, time.Now())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if strings.Contains(buf.String(), "commits:") {
		t.Errorf("expected no header with --no-header, got: %s", buf.String())
	}
}

func TestFailRiskCritical(t *testing.T) { //nolint:paralleltest // uses t.Chdir via setupMiniRepo
	setupMiniRepo(t)

	err := run([]string{"--fail-risk", "critical"}, io.Discard, io.Discard, time.Now())
	if err == nil {
		t.Fatal("expected threshold-exceeded error")
	}

	if code := apierrors.ExitCode(err); code != 2 {
		t.Errorf("ExitCode = %d, want 2 (threshold via --fail-risk)", code)
	}
}
