package main

import (
	"bytes"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/larsartmann/go-hotspot/internal/hotspot"
)

func TestFileFilter(t *testing.T) {
	cases := []struct {
		name     string
		filter   fileFilter
		path     string
		expected bool
	}{
		{"go file, default filter", fileFilter{exts: []string{".go"}}, "main.go", true},
		{"non-go file, .go filter", fileFilter{exts: []string{".go"}}, "script.py", false},
		{"test file, tests excluded", fileFilter{exts: []string{".go"}, includeTests: false}, "main_test.go", false},
		{"test file, tests included", fileFilter{exts: []string{".go"}, includeTests: true}, "main_test.go", true},
		{"generated file, excluded", fileFilter{exts: []string{".go"}}, "foo.pb.go", false},
		{"generated file, included", fileFilter{exts: []string{".go"}, includeGenerated: true}, "foo.pb.go", true},
		{"vendor path excluded", fileFilter{exts: []string{".go"}}, "vendor/lib.go", false},
		{"nested vendor excluded", fileFilter{exts: []string{".go"}}, "foo/vendor/lib.go", false},
		{"path prefix match", fileFilter{exts: []string{".go"}, prefixes: []string{"pkg/"}}, "pkg/main.go", true},
		{"path prefix no match", fileFilter{exts: []string{".go"}, prefixes: []string{"pkg/"}}, "other/main.go", false},
		{"empty prefix ignored", fileFilter{exts: []string{".go"}}, "main.go", true},
		{"no exts = all pass", fileFilter{}, "anything.txt", true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := tc.filter.keep(tc.path); got != tc.expected {
				t.Errorf("keep(%q) = %v, want %v", tc.path, got, tc.expected)
			}
		})
	}
}

func TestIsGenerated(t *testing.T) {
	cases := map[string]bool{
		"foo.pb.go":    true,
		"foo.gen.go":   true,
		"foo_gen.go":   true,
		"foo.pb.gw.go": true,
		"foo.templ.go": true,
		"main.go":      false,
		"generated.go": false,
		"foo.pb.txt":   false,
	}
	for path, want := range cases {
		if got := isGenerated(path); got != want {
			t.Errorf("isGenerated(%q) = %v, want %v", path, got, want)
		}
	}
}

func TestIsGeneratedContent(t *testing.T) {
	dir := t.TempDir()

	genFile := filepath.Join(dir, "generated.go")
	if err := os.WriteFile(
		genFile,
		[]byte("// Code generated by protoc. DO NOT EDIT.\n\npackage main\n"),
		0o600,
	); err != nil {
		t.Fatal(err)
	}

	if !isGeneratedContent(genFile) {
		t.Error("isGeneratedContent should detect generated header")
	}

	normalFile := filepath.Join(dir, "normal.go")
	if err := os.WriteFile(normalFile, []byte("package main\n\nfunc main() {}\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	if isGeneratedContent(normalFile) {
		t.Error("isGeneratedContent should not flag normal files")
	}

	missingFile := filepath.Join(dir, "nonexistent.go")
	if isGeneratedContent(missingFile) {
		t.Error("isGeneratedContent should return false for missing files")
	}
}

func TestParseComplexityMetric(t *testing.T) {
	cases := map[string]hotspot.ComplexityMetric{
		"cyclomatic":  hotspot.MetricCyclomatic,
		"indentation": hotspot.MetricIndentation,
		"indent":      hotspot.MetricIndentation,
		"sloc":        hotspot.MetricSLOC,
		"loc":         hotspot.MetricSLOC,
		"lines":       hotspot.MetricSLOC,
		"unknown":     hotspot.MetricCyclomatic,
	}
	for in, want := range cases {
		if got := parseComplexityMetric(in); got != want {
			t.Errorf("parseComplexityMetric(%q) = %v, want %v", in, got, want)
		}
	}
}

func TestParseChurnMetric(t *testing.T) {
	cases := map[string]hotspot.ChurnMetric{
		"weighted": hotspot.ChurnWeighted,
		"commits":  hotspot.ChurnCommits,
		"commit":   hotspot.ChurnCommits,
		"lines":    hotspot.ChurnLines,
		"raw":      hotspot.ChurnLines,
		"unknown":  hotspot.ChurnWeighted,
	}
	for in, want := range cases {
		if got := parseChurnMetric(in); got != want {
			t.Errorf("parseChurnMetric(%q) = %v, want %v", in, got, want)
		}
	}
}

func TestSplitCSV(t *testing.T) {
	cases := []struct {
		input    string
		expected []string
	}{
		{"", nil},
		{"  ", nil},
		{".go", []string{".go"}},
		{".go,.py,.ts", []string{".go", ".py", ".ts"}},
		{".go, .py , .ts", []string{".go", ".py", ".ts"}},
		{",,", nil},
	}
	for _, tc := range cases {
		got := splitCSV(tc.input)
		if len(got) != len(tc.expected) {
			t.Errorf("splitCSV(%q) = %v, want %v", tc.input, got, tc.expected)

			continue
		}

		for i := range got {
			if got[i] != tc.expected[i] {
				t.Errorf("splitCSV(%q)[%d] = %q, want %q", tc.input, i, got[i], tc.expected[i])
			}
		}
	}
}

func TestHasAuthor(t *testing.T) {
	names := []string{"Alice", "Bob", "Carol"}
	if !hasAuthor(names, "Alice") {
		t.Error("hasAuthor should find Alice")
	}

	if !hasAuthor(names, "alice") {
		t.Error("hasAuthor should be case-insensitive")
	}

	if hasAuthor(names, "Dave") {
		t.Error("hasAuthor should not find Dave")
	}

	if hasAuthor(nil, "Alice") {
		t.Error("hasAuthor should return false for nil slice")
	}
}

func TestRunVersion(t *testing.T) {
	var buf bytes.Buffer

	err := run([]string{"--version"}, &buf, io.Discard, time.Now())
	if err != nil {
		t.Fatalf("run --version returned error: %v", err)
	}

	out := buf.String()
	if !strings.Contains(out, "go-hotspot version") {
		t.Errorf("version output missing header, got: %q", out)
	}
}
